## **Análise Exploratória de Dados (EDA) de denúncias do Disque 100**

#### Análise de subconjunto de denúncias somente sobre tráfico de pessoas

# **1. Informações sobre o conjunto de dados do Disque 100**

O Disque Direitos Humanos - Disque 100 é um serviço de utilidade pública do Ministério dos Direitos Humanos e da Cidadania, conforme previsto no Decreto nº 10.174, de 13 de dezembro de 2019, destinado a receber demandas relativas a violações de Direitos Humanos, especialmente as que atingem populações em situação de vulnerabilidade social[[1]](https://www.gov.br/pt-br/servicos/denunciar-violacao-de-direitos-humanos)[[2]](https://www.gov.br/mdh/pt-br/acesso-a-informacao/disque-100/disque-100)

### Considerações sobre taxonomia de classificação de denúncias

São objetivos centrais:

- padronizar os dados obtidos pela ONDH em formato acessível ao cidadão;
- subsidiar o fomento e fortalecimento de políticas públicas afetas aos direitos humanos;
- racionalizar e uniformizar o fluxo de encaminhamento de denúncias relativas à violação de direitos humanos;
- facilitar o acesso e manejo das informações; e
- aprimorar o fluxo de informações com os demais órgãos governamentais responsáveis pelo recebimento das denúncias de violação aos direitos humanos, aproximando, na medida do possível, às nomenclaturas e estrutura de tabelas taxonômicas empregadas por cada um desses atores.

### Metodologia de embasamento da taxonomia da ONDH

A metodologia apresenta, em detalhe, cada uma das **Classes, Subclasses, Espécies e Subespécies** que a compõe, discriminadas em uma escala de categorização de quatro níveis:

- Nível 01 – Direitos a serem tutelados sob a perspectiva dos direitos humanos.
- Nível 02 – Bem jurídico em sentido estrito.
- Nível 03 – Espécies de violações a determinado bem jurídico protegido.
- Nível 04 – Detalhamento de violações a determinada espécie.

### Violações de direitos humanos extraídas do manual

- 2.Liberdade (Classe) ..........................................................................................................28
- 2.1. Liberdade Laboral (Subclasse) .....................................................................29
- 2.1.1. Exploração do Trabalho (Espécie) ................................................................29
- 2.1.2. Impedimento de Trabalho/Ofício/Profissão (Espécie) ............................29

---

- 2.2.3. Condição Análoga à de Escravo (Espécie) ..................................................31
- 2.2.3.1. Submeter Trabalhador a Trabalhos Forçados (Subespécie) ...................31
- 2.2.3.2. Sujeitar Trabalhador a Condições Degradantes (Subespécie) ..............33
- 2.2.3.3. Submeter Trabalhador a Jornada Exaustiva (Subespécie) ....................34
- 2.2.3.4. Restringir a Locomoção de Trabalhador em Razão de Dívida (Subespécie) ..............................................................35
- 2.2.3.5. Transportar Trabalhador Para Fins de Exploração (Subespécie)..........36

---

- 2.2.8. Tráfico de Pessoas – Internacional (Espécie) ............................................38
- 2.2.9. Tráfico de Pessoas – Nacional (Espécie) ....................................................39

---

- 2.4.2.2. Exploração Sexual (Subespécie) ................................................................44

### Elementos circunstanciais

**Elementos Circunstanciais** (indicadores de gravidade e de motivação) que poderão ser aplicados, conforme o caso concreto que envolva cada relato denunciado.```

- 2.22. Para fins de adoção
- 2.23. Para fins de atividade ilícita
- 2.24. Para fins de exploração sexual
- 2.25. Para fins de remoção de órgãos/tráfico de órgãos
- 2.26. Para fins de exploração do trabalho

Fonte: [Manual de Taxonomia de Direitos Humanos da ONDH](https://www.gov.br/mdh/pt-br/centrais-de-conteudo/publicacoes/ondh/manual-da-taxonomia-de-direitos-humanos-da-ondh.pdf)

In [3]:
# from google.colab import drive

import warnings
import os

import pandas as pd
import numpy as np

from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# import plotly.graph_objects as go
# import plotly.figure_factory as ff
import plotly.io as pio
# from plotly.subplots import make_subplots

pio.templates.default = 'plotly_white'
warnings.filterwarnings('ignore')
pio.renderers.default

'vscode'

In [12]:
disque100 = r"data\trafico-pessoas-outras-violacoes-2021-2025.csv"

In [13]:
df = pd.read_csv(disque100, sep=";")

In [ ]:
df.iloc[:, 1:].reset_index()

:

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8401 entries, 0 to 8400
Data columns (total 63 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Unnamed: 0                                      8401 non-null   int64
 1   hash                                            8401 non-null   str
 2   data_de_cadastro                                8401 non-null   str
 3   canal_de_atendimento                            8401 non-null   str
 4   denuncia_emergencial                            8401 non-null   str
 5   denunciante                                     8401 non-null   str
 6   cenario_da_violacao                             8401 non-null   str
 7   pais                                            8401 non-null   str
 8   uf                                              7828 non-null   str
 9   municipio                                       7810 non-null   str
 10  frequencia                                      8401 non-null   str
 11  inicio_das_violacoes                            8401 non-null   str
 12  sl_quantidade_vitimas                           8401 non-null   int64
 13  grupo_vulneravel                                8401 non-null   str
 14  motivacao                                       2936 non-null   str
 15  relacao_vitima_suspeito                         8401 non-null   str
 16  sl_vitima_cadastro                              8401 non-null   str
 17  genero_da_vitima                                7267 non-null   str
 18  orientacao_sexual_da_vitima                     6030 non-null   str
 19  faixa_etaria_da_vitima                          7996 non-null   str
 20  nacionalidade_da_vitima                         8401 non-null   str
 21  sl_vitima_naturalidade                          318 non-null    str
 22  sl_vitima_naturalizado_uf                       260 non-null    str
 23  sl_vitima_naturalizado_municipio                212 non-null    str
 24  deficiencia_da_vitima                           1988 non-null   str
 25  doenca_rara_da_vitima                           7170 non-null   str
 26  deficiencia_relacionada_a_doenca_rara           187 non-null    str
 27  vitima_preso_a                                  5938 non-null   str
 28  pais_da_vitima                                  8401 non-null   str
 29  uf_da_vitima                                    7813 non-null   str
 30  municipio_da_vitima                             7760 non-null   str
 31  profissao_da_vitima                             1375 non-null   str
 32  grau_de_instrucao_da_vitima                     1658 non-null   str
 33  religiao_da_vitima                              1215 non-null   str
 34  raca_cor_da_vitima                              8191 non-null   str
 35  etnia_da_vitima                                 979 non-null    str
 36  faixa_de_renda_da_vitima                        963 non-null    str
 37  natureza_juridica_do_suspeito                   8401 non-null   str
 38  genero_do_suspeito                              6738 non-null   str
 39  orientacao_sexual_do_suspeito                   6723 non-null   str
 40  faixa_etaria_do_suspeito                        5522 non-null   str
 41  suspeito_nacionalidade                          8392 non-null   str
 42  sl_suspeito_naturalidade                        386 non-null    str
 43  sl_suspeito_naturalizado_uf                     355 non-null    str
 44  sl_suspeito_naturalizado_municipio              270 non-null    str
 45  deficiencia_do_suspeito                         1947 non-null   str
 46  doenca_rara_do_suspeito                         6743 non-null   str
 47  deficiencia_relacionada_a_doenca_rara_suspeito  947 non-null    str
 48  suspeito_preso                                  5513 non-null   str
 49  pais_do_suspeito                                8401 non-null   str
 50  uf_do_suspeito                                  7942 non-null   str
 51  sl_suspeito_municipio                           7896 non-null   str
 52  profissao_do_suspeito                           5603 non-null   str
 53  grau_de_instrucao_do_suspeito                   947 non-null    str
 54  religiao_do_suspeito                            1170 non-null   str
 55  raca_cor_do_suspeito                            4741 non-null   str
 56  suspeito_etnia                                  985 non-null    str
 57  faixa_de_renda_do_suspeito                      947 non-null    str
 58  vinculo_orgao_pj_do_suspeito                    0 non-null      float64
 59  sl_suspeito_ramo                                2396 non-null   str
 60  suspeito_especificacao_etnia                    974 non-null    str
 61  vitima_especificacao_etnia                      991 non-null    str
 62  violacao                                        8211 non-null   str
dtypes: float64(1), int64(2), str(60)
memory usage: 8.4 MB

In [ ]:
df["data_de_cadastro"] = pd.to_datetime(df["data_de_cadastro"], format="mixed")
df["data_de_cadastro"] = df["data_de_cadastro"].dt.floor("s")

In [6]:
df.describe()

                 data_de_cadastro  sl_quantidade_vitimas
count                    13796830           1.379683e+07
mean   2024-03-12 19:08:18.865972           3.166887e+00
min           2021-01-01 00:01:00           1.000000e+00
25%           2023-04-22 08:39:36           1.000000e+00
50%    2024-05-28 16:41:57.500000           1.000000e+00
75%           2025-04-04 09:51:18           2.000000e+00
max           2025-12-31 23:57:15           6.000000e+01
std                           NaN           6.345623e+00

In [7]:
df.to_csv(
    r"C:\Users\deinf.janaelson\Documents\Mestrado\Bases de dados\Disque 100\Juntado\disque100_2021-2025.csv",
    sep=";",
    index=False,
    date_format="%Y-%m-%d %H:%M:%S"
)

In [ ]:
df = pd.read_csv(
    r"C:\Users\deinf.janaelson\Documents\Mestrado\Bases de dados\Disque 100\Juntado\disque100_2021-2025.csv",
    sep=";",
)

### Obter os hashes das "denúncias sobre tráfico de pessoas"

In [9]:
filtro_trafico = df["violacao"].str.contains("TRÁ|AFICO", case=False, regex=True)

In [10]:
df_trafico_pessoas = df[filtro_trafico]

In [11]:
df_trafico_pessoas.shape

(1673, 62)

In [12]:
df_trafico_pessoas.info()

<class 'pandas.DataFrame'>
Index: 1673 entries, 1803 to 13786277
Data columns (total 62 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   hash                                            1673 non-null   str
 1   data_de_cadastro                                1673 non-null   datetime64[us]
 2   canal_de_atendimento                            1673 non-null   str
 3   denuncia_emergencial                            1673 non-null   str
 4   denunciante                                     1673 non-null   str
 5   cenario_da_violacao                             1673 non-null   str
 6   pais                                            1673 non-null   str
 7   uf                                              1599 non-null   str
 8   municipio                                       1593 non-null   str
 9   frequencia                                      1673 non-null   str
 10  inicio_das_violacoes                            1673 non-null   str
 11  sl_quantidade_vitimas                           1673 non-null   int64
 12  grupo_vulneravel                                1673 non-null   str
 13  motivacao                                       551 non-null    str
 14  relacao_vitima_suspeito                         1673 non-null   str
 15  sl_vitima_cadastro                              1673 non-null   str
 16  genero_da_vitima                                1407 non-null   str
 17  orientacao_sexual_da_vitima                     1097 non-null   str
 18  faixa_etaria_da_vitima                          1591 non-null   str
 19  nacionalidade_da_vitima                         1673 non-null   str
 20  sl_vitima_naturalidade                          72 non-null     str
 21  sl_vitima_naturalizado_uf                       57 non-null     str
 22  sl_vitima_naturalizado_municipio                47 non-null     str
 23  deficiencia_da_vitima                           394 non-null    str
 24  doenca_rara_da_vitima                           1384 non-null   str
 25  deficiencia_relacionada_a_doenca_rara           36 non-null     str
 26  vitima_preso_a                                  1088 non-null   str
 27  pais_da_vitima                                  1673 non-null   str
 28  uf_da_vitima                                    1596 non-null   str
 29  municipio_da_vitima                             1584 non-null   str
 30  profissao_da_vitima                             296 non-null    str
 31  grau_de_instrucao_da_vitima                     350 non-null    str
 32  religiao_da_vitima                              240 non-null    str
 33  raca_cor_da_vitima                              1621 non-null   str
 34  etnia_da_vitima                                 198 non-null    str
 35  faixa_de_renda_da_vitima                        197 non-null    str
 36  natureza_juridica_do_suspeito                   1673 non-null   str
 37  genero_do_suspeito                              1408 non-null   str
 38  orientacao_sexual_do_suspeito                   1405 non-null   str
 39  faixa_etaria_do_suspeito                        1199 non-null   str
 40  suspeito_nacionalidade                          1671 non-null   str
 41  sl_suspeito_naturalidade                        81 non-null     str
 42  sl_suspeito_naturalizado_uf                     75 non-null     str
 43  sl_suspeito_naturalizado_municipio              57 non-null     str
 44  deficiencia_do_suspeito                         399 non-null    str
 45  doenca_rara_do_suspeito                         1410 non-null   str
 46  deficiencia_relacionada_a_doenca_rara_suspeito  191 non-null    str
 47  suspeito_preso                                  1202 non-null   str
 48  pais_do_suspeito                                1673 non-null   str
 49  uf_do_suspeito                                  1598 non-null   str
 50  sl_suspeito_municipio                           1585 non-null   str
 51  profissao_do_suspeito                           1224 non-null   str
 52  grau_de_instrucao_do_suspeito                   191 non-null    str
 53  religiao_do_suspeito                            244 non-null    str
 54  raca_cor_do_suspeito                            1043 non-null   str
 55  suspeito_etnia                                  202 non-null    str
 56  faixa_de_renda_do_suspeito                      191 non-null    str
 57  vinculo_orgao_pj_do_suspeito                    0 non-null      str
 58  sl_suspeito_ramo                                419 non-null    str
 59  suspeito_especificacao_etnia                    197 non-null    str
 60  vitima_especificacao_etnia                      203 non-null    str
 61  violacao                                        1673 non-null   str
dtypes: datetime64[us](1), int64(1), str(60)
memory usage: 1.7 MB

In [13]:
df_trafico_pessoas.describe()

                 data_de_cadastro  sl_quantidade_vitimas
count                        1673            1673.000000
mean   2024-04-10 22:54:49.227734               3.433951
min           2021-01-05 08:28:00               1.000000
25%           2023-04-14 18:14:19               1.000000
50%           2024-07-26 20:43:34               1.000000
75%           2025-04-21 13:15:30               2.000000
max           2025-12-30 15:31:58              60.000000
std                           NaN               7.933446

In [14]:
# Salvar arquivo CSV contendo somente dados sobre denúncias de tráfico de pessoas

df_trafico_pessoas.to_csv(r"./data/trafico-pessoas-2021-2025.csv", sep=";")

### Recuperar todas as violações associadas aos hashes das denúncias de tráfico de pessoas

In [15]:
df_trafico_outras = df[df['hash'].isin(df_trafico_pessoas["hash"].values)]

In [16]:
df_trafico_outras.shape

(8401, 62)

In [17]:
df_trafico_outras.info()

<class 'pandas.DataFrame'>
Index: 8401 entries, 877 to 13786277
Data columns (total 62 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   hash                                            8401 non-null   str
 1   data_de_cadastro                                8401 non-null   datetime64[us]
 2   canal_de_atendimento                            8401 non-null   str
 3   denuncia_emergencial                            8401 non-null   str
 4   denunciante                                     8401 non-null   str
 5   cenario_da_violacao                             8401 non-null   str
 6   pais                                            8401 non-null   str
 7   uf                                              7828 non-null   str
 8   municipio                                       7810 non-null   str
 9   frequencia                                      8401 non-null   str
 10  inicio_das_violacoes                            8401 non-null   str
 11  sl_quantidade_vitimas                           8401 non-null   int64
 12  grupo_vulneravel                                8401 non-null   str
 13  motivacao                                       2936 non-null   str
 14  relacao_vitima_suspeito                         8401 non-null   str
 15  sl_vitima_cadastro                              8401 non-null   str
 16  genero_da_vitima                                7267 non-null   str
 17  orientacao_sexual_da_vitima                     6030 non-null   str
 18  faixa_etaria_da_vitima                          7996 non-null   str
 19  nacionalidade_da_vitima                         8401 non-null   str
 20  sl_vitima_naturalidade                          318 non-null    str
 21  sl_vitima_naturalizado_uf                       260 non-null    str
 22  sl_vitima_naturalizado_municipio                212 non-null    str
 23  deficiencia_da_vitima                           1988 non-null   str
 24  doenca_rara_da_vitima                           7170 non-null   str
 25  deficiencia_relacionada_a_doenca_rara           187 non-null    str
 26  vitima_preso_a                                  5938 non-null   str
 27  pais_da_vitima                                  8401 non-null   str
 28  uf_da_vitima                                    7813 non-null   str
 29  municipio_da_vitima                             7760 non-null   str
 30  profissao_da_vitima                             1375 non-null   str
 31  grau_de_instrucao_da_vitima                     1658 non-null   str
 32  religiao_da_vitima                              1215 non-null   str
 33  raca_cor_da_vitima                              8191 non-null   str
 34  etnia_da_vitima                                 979 non-null    str
 35  faixa_de_renda_da_vitima                        963 non-null    str
 36  natureza_juridica_do_suspeito                   8401 non-null   str
 37  genero_do_suspeito                              6738 non-null   str
 38  orientacao_sexual_do_suspeito                   6723 non-null   str
 39  faixa_etaria_do_suspeito                        5522 non-null   str
 40  suspeito_nacionalidade                          8392 non-null   str
 41  sl_suspeito_naturalidade                        386 non-null    str
 42  sl_suspeito_naturalizado_uf                     355 non-null    str
 43  sl_suspeito_naturalizado_municipio              270 non-null    str
 44  deficiencia_do_suspeito                         1947 non-null   str
 45  doenca_rara_do_suspeito                         6743 non-null   str
 46  deficiencia_relacionada_a_doenca_rara_suspeito  947 non-null    str
 47  suspeito_preso                                  5513 non-null   str
 48  pais_do_suspeito                                8401 non-null   str
 49  uf_do_suspeito                                  7942 non-null   str
 50  sl_suspeito_municipio                           7896 non-null   str
 51  profissao_do_suspeito                           5603 non-null   str
 52  grau_de_instrucao_do_suspeito                   947 non-null    str
 53  religiao_do_suspeito                            1170 non-null   str
 54  raca_cor_do_suspeito                            4741 non-null   str
 55  suspeito_etnia                                  985 non-null    str
 56  faixa_de_renda_do_suspeito                      947 non-null    str
 57  vinculo_orgao_pj_do_suspeito                    0 non-null      str
 58  sl_suspeito_ramo                                2396 non-null   str
 59  suspeito_especificacao_etnia                    974 non-null    str
 60  vitima_especificacao_etnia                      991 non-null    str
 61  violacao                                        8211 non-null   str
dtypes: datetime64[us](1), int64(1), str(60)
memory usage: 8.3 MB

In [ ]:
df_trafico_outras.head()

In [2]:
df_trafico_outras.to_csv(r"./data/trafico-pessoas-outras-violacoes-2021-2025.csv", sep=";")

NameError: name 'df_trafico_outras' is not defined

### Análise de valores ausentes

In [ ]:
df_trafico_pessoas.isna().sum().sum() / df_trafico_pessoas.size

np.float64(0.38967086362146425)

In [19]:
df_trafico_outras.isna().sum().sum()

np.int64(205812)

### Separar níveis de classificação taxonômica da coluna "violação"

In [20]:
df_trafico_outras['violacao'].apply(
    lambda x: str(x).split(">") if pd.notna(x) else []
)

877                          [INTEGRIDADE, PSÍQUICA, CALÚNIA]
1733                [INTEGRIDADE, PSÍQUICA, AMEAÇA ou COAÇÃO]
1803        [LIBERDADE, DIREITOS INDIVIDUAIS, TRÁFICO DE P...
2488        [LIBERDADE, DIREITOS INDIVIDUAIS, TRÁFICO DE P...
2503        [LIBERDADE, DIREITOS INDIVIDUAIS, CÁRCERE PRIV...
                                  ...
13759776    [LIBERDADE, DIREITOS INDIVIDUAIS, TRÁFICO DE M...
13759777             [INTEGRIDADE, PSÍQUICA, CONSTRANGIMENTO]
13759778    [INTEGRIDADE, FÍSICA, EXPOSIÇÃO DE RISCO À SAÚDE]
13786276                           [INTEGRIDADE, NEGLIGÊNCIA]
13786277    [LIBERDADE, DIREITOS INDIVIDUAIS, TRÁFICO DE C...
Name: violacao, Length: 8401, dtype: object

In [21]:
taxonomia_violacoes = df_trafico_outras['violacao'].str.split(">", expand=True)

taxonomia_violacoes.columns = [
    f'violacao_nivel_{i+1}' for i in range(taxonomia_violacoes.shape[1])
]

df_trafico_outras = pd.concat(
    [df_trafico_outras, taxonomia_violacoes],
    axis=1
)

In [22]:
df_trafico_outras.tail()

,hash,data_de_cadastro,canal_de_atendimento,denuncia_emergencial,denunciante,cenario_da_violacao,pais,uf,municipio,frequencia,...,faixa_de_renda_do_suspeito,vinculo_orgao_pj_do_suspeito,sl_suspeito_ramo,suspeito_especificacao_etnia,vitima_especificacao_etnia,violacao,violacao_nivel_1,violacao_nivel_2,violacao_nivel_3,violacao_nivel_4
13759776,F4860AB6BDB19189CFBDDD135390F5B13A54B501F96C04...,2025-12-28 14:53:31,TELEFÔNICO,NÃO,TERCEIRO,LOCAL DE TRABALHO DA VÍTIMA,BR | BRASIL,SP,3547304 | SANTANA DE PARNAÍBA,DIARIAMENTE,...,NaN,NaN,NaN,NaN,NaN,LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE MULH...,LIBERDADE,DIREITOS INDIVIDUAIS,TRÁFICO DE MULHERES - NACIONAL,NaN
13759777,F4860AB6BDB19189CFBDDD135390F5B13A54B501F96C04...,2025-12-28 14:53:31,TELEFÔNICO,NÃO,TERCEIRO,LOCAL DE TRABALHO DA VÍTIMA,BR | BRASIL,SP,3547304 | SANTANA DE PARNAÍBA,DIARIAMENTE,...,NaN,NaN,NaN,NaN,NaN,INTEGRIDADE>PSÍQUICA>CONSTRANGIMENTO,INTEGRIDADE,PSÍQUICA,CONSTRANGIMENTO,NaN
13759778,F4860AB6BDB19189CFBDDD135390F5B13A54B501F96C04...,2025-12-28 14:53:31,TELEFÔNICO,NÃO,TERCEIRO,LOCAL DE TRABALHO DA VÍTIMA,BR | BRASIL,SP,3547304 | SANTANA DE PARNAÍBA,DIARIAMENTE,...,NaN,NaN,NaN,NaN,NaN,INTEGRIDADE>FÍSICA>EXPOSIÇÃO DE RISCO À SAÚDE,INTEGRIDADE,FÍSICA,EXPOSIÇÃO DE RISCO À SAÚDE,NaN
13786276,4B7FDF48CC4EFD828AED3C6B9F7F6A1AF155301685DF1F...,2025-12-30 15:31:58,WHATSAPP,NÃO,TERCEIRO,CASA ONDE RESIDE A VÍTIMA E O SUSPEITO,BR | BRASIL,RS,4306106 | CRUZ ALTA,DIARIAMENTE,...,NaN,NaN,NaN,NaN,NaN,INTEGRIDADE>NEGLIGÊNCIA,INTEGRIDADE,NEGLIGÊNCIA,NaN,NaN
13786277,4B7FDF48CC4EFD828AED3C6B9F7F6A1AF155301685DF1F...,2025-12-30 15:31:58,WHATSAPP,NÃO,TERCEIRO,CASA ONDE RESIDE A VÍTIMA E O SUSPEITO,BR | BRASIL,RS,4306106 | CRUZ ALTA,DIARIAMENTE,...,NaN,NaN,NaN,NaN,NaN,LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE CRIA...,LIBERDADE,DIREITOS INDIVIDUAIS,TRÁFICO DE CRIANÇAS - NACIONAL,NaN

### Separar tipo de tráfico da abrangência territorial

In [23]:
df_trafico_outras[['violacao_nivel_3_normalizada', 'violacao_abrangencia']] = (
    df_trafico_outras['violacao_nivel_3']
    .str.split(' - ', n=1, expand=True)
)

In [24]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [25]:
df_trafico_outras.tail()

,hash,data_de_cadastro,canal_de_atendimento,denuncia_emergencial,denunciante,cenario_da_violacao,pais,uf,municipio,frequencia,...,sl_suspeito_ramo,suspeito_especificacao_etnia,vitima_especificacao_etnia,violacao,violacao_nivel_1,violacao_nivel_2,violacao_nivel_3,violacao_nivel_4,violacao_nivel_3_normalizada,violacao_abrangencia
13759776,F4860AB6BDB19189CFBDDD135390F5B13A54B501F96C04...,2025-12-28 14:53:31,TELEFÔNICO,NÃO,TERCEIRO,LOCAL DE TRABALHO DA VÍTIMA,BR | BRASIL,SP,3547304 | SANTANA DE PARNAÍBA,DIARIAMENTE,...,NaN,NaN,NaN,LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE MULH...,LIBERDADE,DIREITOS INDIVIDUAIS,TRÁFICO DE MULHERES - NACIONAL,NaN,TRÁFICO DE MULHERES,NACIONAL
13759777,F4860AB6BDB19189CFBDDD135390F5B13A54B501F96C04...,2025-12-28 14:53:31,TELEFÔNICO,NÃO,TERCEIRO,LOCAL DE TRABALHO DA VÍTIMA,BR | BRASIL,SP,3547304 | SANTANA DE PARNAÍBA,DIARIAMENTE,...,NaN,NaN,NaN,INTEGRIDADE>PSÍQUICA>CONSTRANGIMENTO,INTEGRIDADE,PSÍQUICA,CONSTRANGIMENTO,NaN,CONSTRANGIMENTO,NaN
13759778,F4860AB6BDB19189CFBDDD135390F5B13A54B501F96C04...,2025-12-28 14:53:31,TELEFÔNICO,NÃO,TERCEIRO,LOCAL DE TRABALHO DA VÍTIMA,BR | BRASIL,SP,3547304 | SANTANA DE PARNAÍBA,DIARIAMENTE,...,NaN,NaN,NaN,INTEGRIDADE>FÍSICA>EXPOSIÇÃO DE RISCO À SAÚDE,INTEGRIDADE,FÍSICA,EXPOSIÇÃO DE RISCO À SAÚDE,NaN,EXPOSIÇÃO DE RISCO À SAÚDE,NaN
13786276,4B7FDF48CC4EFD828AED3C6B9F7F6A1AF155301685DF1F...,2025-12-30 15:31:58,WHATSAPP,NÃO,TERCEIRO,CASA ONDE RESIDE A VÍTIMA E O SUSPEITO,BR | BRASIL,RS,4306106 | CRUZ ALTA,DIARIAMENTE,...,NaN,NaN,NaN,INTEGRIDADE>NEGLIGÊNCIA,INTEGRIDADE,NEGLIGÊNCIA,NaN,NaN,NaN,NaN
13786277,4B7FDF48CC4EFD828AED3C6B9F7F6A1AF155301685DF1F...,2025-12-30 15:31:58,WHATSAPP,NÃO,TERCEIRO,CASA ONDE RESIDE A VÍTIMA E O SUSPEITO,BR | BRASIL,RS,4306106 | CRUZ ALTA,DIARIAMENTE,...,NaN,NaN,NaN,LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE CRIA...,LIBERDADE,DIREITOS INDIVIDUAIS,TRÁFICO DE CRIANÇAS - NACIONAL,NaN,TRÁFICO DE CRIANÇAS,NACIONAL

In [26]:
df_trafico_outras["uf"].value_counts()

uf
SP                                1797
MG                                 975
DENUNCIANTE NÃO SOUBE INFORMAR     773
RJ                                 611
RS                                 514
CE                                 325
BA                                 287
PR                                 276
PE                                 231
AM                                 210
GO                                 200
RN                                 193
MS                                 191
DF                                 177
SC                                 153
ES                                 138
N/D                                136
RR                                 128
SE                                 101
AC                                  93
PA                                  74
MA                                  56
RO                                  50
PB                                  41
MT                                  39
ATENDIMENTO INTERROMPIDO            18
AP                                  14
TO                                  14
AL                                  10
PI                                   3
Name: count, dtype: int64

In [27]:
df_trafico_outras[['violacao_nivel_3_normalizada', 'violacao_abrangencia']] = (
    df_trafico_outras['pais']
    .str.split(' - ', n=1, expand=True)
)


# Substituição de valores ausentes
# df_trafico_outras['abrangencia'] = (
#     df_trafico_outras['abrangencia']
#     .replace('', pd.NA)
# )

ValueError: Columns must be same length as key

### Normalizar variáveis geográficas

- Geral
  - pais
  - municipio
- Vítima
  - nacionalidade_da_vitima
  - pais_da_vitima
  - municipio_da_vitima
- Suspeito
  - suspeito_nacionalidade
  - pais_do_suspeito
  - sl_suspeito_municipio

In [ ]:
import pandas as pd

# Variáveis geográficas
colunas_geo = [
    'pais',
    'municipio',
    'nacionalidade_da_vitima',
    'pais_da_vitima',
    'municipio_da_vitima',
    'suspeito_nacionalidade',
    'pais_do_suspeito',
    'sl_suspeito_municipio'
]

for coluna in colunas_geo:

    # Divide apenas no primeiro pipe encontrado
    split = df_trafico_outras[coluna].astype(str).str.split('|', n=1, expand=True)

    if split.shape[1] == 2:
        df_trafico_outras[f'{coluna}_codigo'] = split[0].str.strip()
        df_trafico_outras[f'{coluna}_nome'] = split[1].str.strip()

        # Se não havia pipe, o valor foi para a coluna da esquerda
        sem_pipe = split[1].isna()

        df_trafico_outras.loc[sem_pipe, f'{coluna}_nome'] = split.loc[sem_pipe, 0]
        df_trafico_outras.loc[sem_pipe, f'{coluna}_codigo'] = pd.NA

    else:
        df_trafico_outras[f'{coluna}_codigo'] = pd.NA
        df_trafico_outras[f'{coluna}_nome'] = split[0].str.strip()

In [ ]:
threshold = 0.3
cols_missing_values = (df_trafico_pessoas.isna().mean() > threshold).tolist()

### Registros únicos

In [ ]:
df_trafico_pessoas.nunique().sort_values(ascending=False)

hash                                              1263
data_de_cadastro                                   640
sl_suspeito_municipio                              327
municipio                                          313
municipio_da_vitima                                301
motivacao                                           54
profissao_do_suspeito                               51
relacao_vitima_suspeito                             43
faixa_etaria_da_vitima                              40
sl_suspeito_naturalizado_municipio                  31
uf_do_suspeito                                      30
uf_da_vitima                                        30
uf                                                  30
pais_do_suspeito                                    30
pais                                                29
cenario_da_violacao                                 28
sl_suspeito_ramo                                    28
sl_vitima_naturalizado_municipio                    25
pais_da_vitima                                      22
suspeito_nacionalidade                              20
faixa_etaria_do_suspeito                            19
sl_vitima_naturalizado_uf                           16
sl_suspeito_naturalizado_uf                         14
religiao_do_suspeito                                13
religiao_da_vitima                                  11
profissao_da_vitima                                 11
orientacao_sexual_do_suspeito                       11
nacionalidade_da_vitima                             10
sl_quantidade_vitimas                               10
orientacao_sexual_da_vitima                         10
grupo_vulneravel                                     9
suspeito_preso                                       9
grau_de_instrucao_da_vitima                          9
inicio_das_violacoes                                 9
canal_de_atendimento                                 8
grau_de_instrucao_do_suspeito                        7
faixa_de_renda_da_vitima                             7
raca_cor_da_vitima                                   7
frequencia                                           7
denunciante                                          6
violacao                                             6
raca_cor_do_suspeito                                 6
genero_do_suspeito                                   6
natureza_juridica_do_suspeito                        6
deficiencia_da_vitima                                6
genero_da_vitima                                     6
faixa_de_renda_do_suspeito                           5
denuncia_emergencial                                 5
deficiencia_do_suspeito                              5
etnia_da_vitima                                      4
sl_vitima_cadastro                                   4
suspeito_especificacao_etnia                         4
doenca_rara_da_vitima                                3
vitima_preso_a                                       3
suspeito_etnia                                       3
doenca_rara_do_suspeito                              3
vitima_especificacao_etnia                           3
deficiencia_relacionada_a_doenca_rara                2
deficiencia_relacionada_a_doenca_rara_suspeito       2
sl_suspeito_naturalidade                             2
sl_vitima_naturalidade                               1
vinculo_orgao_pj_do_suspeito                         0
dtype: int64

In [ ]:
df_trafico_outras.nunique().sort_values(ascending=False)

NameError: name 'df_trafico_outras' is not defined

In [ ]:
import pandas

### Obter os hashes que possuem Tráfico de Pessoas

In [ ]:
df_resultado["violacao"].value_counts()

violacao
LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE CRIANÇAS - NACIONAL         524
LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE PESSOAS - NACIONAL          381
LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE PESSOAS - INTERNACIONAL     372
LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE CRIANÇAS - INTERNACIONAL    185
LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE MULHERES - INTERNACIONAL    118
LIBERDADE>DIREITOS INDIVIDUAIS>TRÁFICO DE MULHERES - NACIONAL          93
Name: count, dtype: int64

In [ ]:
import pandas as pd
import numpy as np

# Split tratando NaN
df_filtrado['niveis'] = df_filtrado['violacao'].apply(
    lambda x: str(x).split(">") if pd.notna(x) else []
)

# Limpar espaços
df_filtrado['niveis'] = df_filtrado['niveis'].apply(lambda x: [i.strip() for i in x if i.strip()])

max_niveis = df_filtrado['niveis'].str.len().max()

niveis_expandidos = pd.DataFrame(
    df_filtrado['niveis'].tolist(),
    columns=[f'nivel_{i+1}' for i in range(max_niveis)]
)

df_filtrado = pd.concat([df_filtrado, niveis_expandidos], axis=1)

df_filtrado = df_filtrado.drop(columns='niveis')

In [ ]:
df_filtrado

In [ ]:
cols_missing_values

In [ ]:
# Consumir API Sidra IBGE Pobreza
# Para consumir a API Sidra do IBGE relacionada à pobreza, os desenvolvedores podem seguir os seguintes passos:
# Acesse a API Sidra: Utilize o URL https://apisidra.ibge.gov.br/DescritoresTabela/t/<tabela>
# https://apisidra.ibge.gov.br/DescritoresTabela/t/
# Tabela 6397: Taxas de desocupação e de subutilização da força de ...

In [ ]:
import requests

response = requests.get("https://apisidra.ibge.gov.br/DescritoresTabela/t/6397")

In [ ]:
response.status_code

In [ ]:
response.json()

### **Nova Análise Exploratória de Dados**

In [28]:
# from google.colab import drive

import warnings
import os

import pandas as pd
import numpy as np

from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# import plotly.graph_objects as go
# import plotly.figure_factory as ff
import plotly.io as pio
# from plotly.subplots import make_subplots

pio.templates.default = 'plotly_white'
warnings.filterwarnings('ignore')
pio.renderers.default

pd.set_option('display.max_rows', 75)

In [29]:
disque100_filepath = r"C:\Users\deinf.janaelson\Documents\Mestrado\Bases de dados\Disque 100\Juntado\disque100-2021_2025.csv"

In [30]:
df = pd.read_csv(disque100_filepath, sep=";", encoding="utf-8", parse_dates=["data_de_cadastro"])

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\deinf.janaelson\\Documents\\Mestrado\\Bases de dados\\Disque 100\\Juntado\\disque100-2021_2025.csv'

In [ ]:
df.info()

## **Exploratory Data Analysis (EDA)**

estudar as principais características do tráfico de pessoas no Brasil e como elas são distribuídas.

1. Data Loading
   Import necessary libraries (pandas, numpy, matplotlib, seaborn, etc.).
   Load dataset from CSV, Excel, SQL, API, or other sources.
   Example:
   Python

Copiar código
import pandas as pd

df = pd.read_csv("data.csv") 2. Data Overview
Shape: df.shape → number of rows and columns.
Preview: df.head() and df.tail().
Column names & types: df.info().
Basic statistics: df.describe() for numerical data. 3. Data Cleaning
Missing values: df.isnull().sum().
Duplicates: df.duplicated().sum().
Data type corrections: Convert to datetime, category, etc.
Outlier detection: Using IQR or z-score. 4. Univariate Analysis
Distribution of each variable.
Histograms, boxplots, and value counts for categorical features.
Example:
Python

Copiar código
import seaborn as sns
sns.histplot(df['age'], kde=True) 5. Bivariate / Multivariate Analysis
Relationships between variables.
Scatter plots, correlation heatmaps, grouped statistics.
Example:
Python

Copiar código
sns.heatmap(df.corr(), annot=True, cmap="coolwarm") 6. Feature Relationships & Insights
Grouping and aggregation: df.groupby('category')['value'].mean().
Cross-tabulations for categorical variables. 7. Outlier & Anomaly Detection
Boxplots, z-scores, IQR method.
Decide whether to remove, cap, or transform. 8. Data Transformation (if needed)
Scaling, normalization, encoding categorical variables.
Log transformations for skewed data. 9. Summary & Key Findings
Bullet points summarizing patterns, anomalies, and potential next steps.
This section is crucial for communicating results to stakeholders.
✅ Tip: In practice, these sections are often implemented in a Jupyter Notebook so that code, visualizations, and explanations are combined.

If you want, I can prepare a ready-to-run Python Pandas EDA template that includes all these sections so you can just plug in your dataset and run it.
Do you want me to create that?

1. Data Loading
   Import necessary libraries (pandas, numpy, matplotlib, seaborn, etc.).
   Load dataset from CSV, Excel, SQL, API, or other sources.
   Example:

```
import pandas as pd

df = pd.read_csv("data.csv")

```

2. Data Overview
   Shape: df.shape → number of rows and columns.
   Preview: df.head() and df.tail().
   Column names & types: df.info().
   Basic statistics: df.describe() for numerical data.

3. Data Cleaning
   Missing values: df.isnull().sum().
   Duplicates: df.duplicated().sum().
   Data type corrections: Convert to datetime, category, etc.
   Outlier detection: Using IQR or z-score.

4. Univariate Analysis
   Distribution of each variable.
   Histograms, boxplots, and value counts for categorical features.
   Example:

```
import seaborn as sns
sns.histplot(df['age'], kde=True)
```

5. Bivariate / Multivariate Analysis
   Relationships between variables.
   Scatter plots, correlation heatmaps, grouped statistics.
   Example:

```
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
```

6. Feature Relationships & Insights
   Grouping and aggregation: df.groupby('category')['value'].mean().
   Cross-tabulations for categorical variables.

7. Outlier & Anomaly Detection
   Boxplots, z-scores, IQR method.
   Decide whether to remove, cap, or transform.

8. Data Transformation (if needed)
   Scaling, normalization, encoding categorical variables.
   Log transformations for skewed data.

9. Summary & Key Findings
   Bullet points summarizing patterns, anomalies, and potential next steps.
   This section is crucial for communicating results to stakeholders.
   ✅ Tip: In practice, these sections are often implemented in a Jupyter Notebook so that code, visualizations, and explanations are combined.

In [31]:
# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display settings for better readability
pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

# =========================
# 2. Load Dataset
# =========================
try:
    df = pd.read_csv("your_dataset.csv")  # Change to your dataset path
except FileNotFoundError:
    raise FileNotFoundError("Dataset file not found. Please check the path.")

# =========================
# 3. Data Overview
# =========================
print("\n--- Dataset Shape ---")
print(df.shape)

print("\n--- First 5 Rows ---")
print(df.head())

print("\n--- Data Types & Non-Null Counts ---")
print(df.info())

print("\n--- Basic Statistics ---")
print(df.describe(include='all').transpose())

# =========================
# 4. Data Cleaning
# =========================
print("\n--- Missing Values ---")
print(df.isnull().sum())

print("\n--- Duplicate Rows ---")
print(df.duplicated().sum())

# Example: Drop duplicates if needed
# df = df.drop_duplicates()

# Convert date columns if applicable
# df['date_column'] = pd.to_datetime(df['date_column'], errors='coerce')

# =========================
# 5. Univariate Analysis
# =========================
# Numerical features distribution
num_cols = df.select_dtypes(include=np.number).columns
for col in num_cols:
    plt.figure(figsize=(6, 4))
    sns.histplot(df[col], kde=True, bins=30)
    plt.title(f"Distribution of {col}")
    plt.show()

# Categorical features distribution
cat_cols = df.select_dtypes(exclude=np.number).columns
for col in cat_cols:
    plt.figure(figsize=(6, 4))
    sns.countplot(y=df[col], order=df[col].value_counts().index)
    plt.title(f"Count of {col}")
    plt.show()

# =========================
# 6. Bivariate / Multivariate Analysis
# =========================
# Correlation heatmap for numerical features
if len(num_cols) > 1:
    plt.figure(figsize=(10, 6))
    sns.heatmap(df[num_cols].corr(), annot=True, cmap="coolwarm", fmt=".2f")
    plt.title("Correlation Heatmap")
    plt.show()

# Example scatter plot
if len(num_cols) >= 2:
    plt.figure(figsize=(6, 4))
    sns.scatterplot(x=num_cols[0], y=num_cols[1], data=df)
    plt.title(f"{num_cols[0]} vs {num_cols[1]}")
    plt.show()

# =========================
# 7. Outlier Detection
# =========================
for col in num_cols:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.show()

# =========================
# 8. Feature Relationships & Grouping
# =========================
# Example: Mean value by category
for col in cat_cols:
    for num in num_cols:
        grouped = df.groupby(col)[num].mean().sort_values(ascending=False)
        print(f"\nMean {num} by {col}:\n", grouped)

# =========================
# 9. Summary & Key Findings
# =========================
print("\n--- Summary & Key Findings ---")
print("1. Dataset shape:", df.shape)
print("2. Missing values found in:", df.columns[df.isnull().any()].tolist())
print("3. Numerical features:", list(num_cols))
print("4. Categorical features:", list(cat_cols))
print("5. Potential outliers detected in boxplots above.")

FileNotFoundError: Dataset file not found. Please check the path.

References:

https://www.youtube.com/watch?v=xi0vhXFPegw
https://www.kaggle.com/code/robikscube/introduction-to-exploratory-data-analysis#Step-3:-Feature-Understanding
https://www.kaggle.com/code/kashnitsky/topic-1-exploratory-data-analysis-with-pandas
https://www.datacamp.com/tutorial/exploratory-data-analysis-python
https://www.geeksforgeeks.org/data-analysis/exploratory-data-analysis-in-python/
https://github.com/hoffm386/eda-with-categorical-variables
https://www.kaggle.com/code/nextbigwhat/eda-for-categorical-variables-a-beginner-s-way
https://www.kaggle.com/code/nextbigwhat/eda-for-categorical-variables-a-beginner-s-way
https://readmedium.com/mastering-exploratory-data-analysis-eda-everything-you-need-to-know-7e3b48d63a95
https://www.datacamp.com/tutorial/kaggle-machine-learning-eda
https://towardsdatascience.com/exploratory-data-analysis-in-python-a-step-by-step-process-d0dfa6bf94ee/